# Linear regression을 활용한 부동산 예측

## 1.Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
from visdom import Visdom
viz = Visdom()

WARNING:root:Setting up a new session...

## 2. Data Loader

In [2]:
num_data=1000
num_epoch=200

import pandas as pd # 엑셀 데이터 처리를 위한 pandas패키지 로드

df = pd.read_csv("price.csv", parse_dates =["date"], index_col ="date")  #엑셀 파일을 읽어 df변수에 저장
df = df.dropna()
#df=(df-df.mean())/df.std()
#df=(df-df.min())/(df.max()-df.min())+0.0001

df.head()

,tradeprice_sido_n1,region_cd,tradeprice_sido,year,month,building_type,construction_realized_amount,cd,spirit_deposit_rate,exchange_rate,composite_stock_price_index,economy_growth,exchequer_bond_three,household_loan_all,mortgage_all,numberofnosells,unsalenum_c
date,,,,,,,,,,,,,,,,,
2010-01-01,93.4,45000,93.3,2010,1,7,6500576.0,2.88,3.93,1156.5,1682.16,2.2,4.29,548723.3,338666.3,0.0,0.0
2010-01-01,83.9,30000,83.1,2010,1,0,6500576.0,2.88,3.93,1156.5,1682.16,2.2,4.29,548723.3,338666.3,3042.0,323.0
2010-01-01,92.7,30000,92.3,2010,1,7,6500576.0,2.88,3.93,1156.5,1682.16,2.2,4.29,548723.3,338666.3,3042.0,323.0
2010-01-01,80.8,30000,79.7,2010,1,1,6500576.0,2.88,3.93,1156.5,1682.16,2.2,4.29,548723.3,338666.3,3042.0,323.0
2010-01-01,81.8,30000,81.8,2010,1,3,6500576.0,2.88,3.93,1156.5,1682.16,2.2,4.29,548723.3,338666.3,3042.0,323.0

In [3]:
df.resample(rule='A').mean() #연도별로 통계를 내보자

,tradeprice_sido_n1,region_cd,tradeprice_sido,year,month,building_type,construction_realized_amount,cd,spirit_deposit_rate,exchange_rate,composite_stock_price_index,economy_growth,exchequer_bond_three,household_loan_all,mortgage_all,numberofnosells,unsalenum_c
date,,,,,,,,,,,,,,,,,
2010-12-31,85.678906,36750.000000,85.469271,2010.0,6.500000,2.75,7.689668e+06,2.671667,3.181667,1159.400000,1761.925833,1.475000,3.718333,568365.566667,349610.691667,1236.640625,541.677083
2011-12-31,90.873037,36727.748691,90.302749,2011.0,6.502618,2.75,7.633607e+06,3.437016,3.686492,1107.846597,1983.284188,0.725654,3.620681,615922.894764,377893.788482,683.026178,423.408377
2012-12-31,94.025387,36742.268041,94.015464,2012.0,6.551546,2.75,7.411050e+06,3.293041,3.424485,1124.052577,1931.431649,0.526804,3.130155,645835.318557,396972.789175,454.520619,186.876289
2013-12-31,94.198652,36705.882353,94.098775,2013.0,6.500000,2.75,8.174064e+06,2.722500,2.703333,1095.433333,1961.248333,0.850000,2.793333,666946.983333,406966.191667,547.215686,239.333333
2014-12-31,95.477340,36684.729064,95.375739,2014.0,6.507389,2.75,8.207670e+06,2.490887,2.420099,1052.333990,1982.338030,0.700493,2.591281,710863.112315,436247.054187,248.014778,108.068966
2015-12-31,97.420098,36705.882353,97.220221,2015.0,6.500000,2.75,8.551165e+06,1.770000,1.719167,1133.083333,2010.792500,0.800000,1.799167,772351.316667,476190.525000,180.446078,62.382353
2016-12-31,98.678342,36653.465347,98.643317,2016.0,6.514851,2.75,1.001116e+07,1.493317,1.466188,1163.131188,1986.238416,0.626238,1.441683,859289.918317,518222.086634,341.965347,50.356436
2017-12-31,99.529774,36608.040201,99.435427,2017.0,6.512563,2.75,1.152759e+07,1.444372,1.514221,1122.084422,2312.495829,0.704523,1.805427,939928.797487,561827.164322,541.894472,93.417085
2018-12-31,100.211224,36571.428571,100.162755,2018.0,2.000000,2.75,1.073421e+07,1.653265,1.769592,1069.693878,2469.895102,1.000000,2.247347,980192.414286,580582.510204,358.591837,58.204082

In [4]:
'''
‘region_cd’: ‘지역코드(시도)’,
‘year’: ‘연도’,
‘month’:’월’,
‘building_type’: ‘부동산타입’,
‘tradeprice_sido’ : ‘매매가격지수(시도)’,
‘construction_realized_amount’ : ‘건설기성액(백만원)’,
“cd”: “cd(91일물)“,
‘spirit_deposit_rate’: ‘정기예금금리’,
‘exchange_rate’: ‘환율’,
‘composite_stock_price_index’: ‘종합주가지수’,
‘economy_growth’: ‘경제성장률’,
‘exchequer_bond_three’ : ‘국고채3년‘,
‘household_loan_all’: ‘가계대출액(전국)’,
‘mortgage_all’ : ‘주택대출액(전국)’,
‘numberofnosells’:’미분양 가구수(시도)’,
‘unsalenum_c’:’공사완료후 미분양(민간,시도)’
'''
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result


#train = df[(df.year > 2006) & (df.year < 2017) & (df.region_cd == 45000)]
#test = df[df.year >= 2017 & (df.region_cd == 45000)]
train = df[(df.year > 2006) & (df.year < 2017)]
test = df[df.year >= 2017]
train = normalize(train) # 데이터를 normalize해서 0~1사이 값으로 다 바꿈!
test = normalize(test)  # 데이터를 normalize해서 0~1사이 값으로 다 바꿈!
'''
feature_names = ['region_cd', 'year', 'month', 'building_type',
                 'tradeprice_sido', 'construction_realized_amount','cd',
                 'spirit_deposit_rate','exchange_rate','composite_stock_price_index',
                 'economy_growth','exchequer_bond_three','household_loan_all',
                 'mortgage_all','numberofnosells','unsalenum_c']  # 학습에 사용될 항목들을 설정
'''
feature_names = [
                 'tradeprice_sido','cd',
                 'spirit_deposit_rate','exchange_rate','composite_stock_price_index',
                 'economy_growth','exchequer_bond_three','household_loan_all',
                 'mortgage_all','numberofnosells','unsalenum_c']  # 학습에 사용될 항목들을 설정

input_dim = len(feature_names) # 학습에 사용될 항목들의 갯수 == 한개의 input의 feature 갯수
X_train = train[feature_names]
X_test = test[feature_names]

lable_name = "tradeprice_sido_n1"  # 어떤 값을 예측값으로 넣을것인가 이 경우 다음달 매매가격지수를 예측하도록함
Y_train = train[lable_name]
Y_test = test[lable_name]


print(X_train.shape)
print(X_test.shape)
X_train.head()  #데이터가 어떻게 생겼나 보는 함수

(336, 11)
(6552, 11)

,tradeprice_sido,cd,spirit_deposit_rate,exchange_rate,composite_stock_price_index,economy_growth,exchequer_bond_three,household_loan_all,mortgage_all,numberofnosells,unsalenum_c
date,,,,,,,,,,,
2010-01-01,0.559846,0.684444,1.000000,0.644274,0.150134,1.0,1.000000,0.000000,0.000000,0.0,0.0
2010-01-01,0.173745,0.684444,1.000000,0.644274,0.150134,1.0,1.000000,0.000000,0.000000,0.0,0.0
2010-01-01,0.000000,0.684444,1.000000,0.644274,0.150134,1.0,1.000000,0.000000,0.000000,0.0,0.0
2010-01-01,0.204633,0.684444,1.000000,0.644274,0.150134,1.0,1.000000,0.000000,0.000000,0.0,0.0
2010-02-01,0.563707,0.684444,0.878327,0.652840,0.000000,1.0,0.967427,0.002055,0.005208,0.0,0.0

In [5]:
X_test.head()

,tradeprice_sido,cd,spirit_deposit_rate,exchange_rate,composite_stock_price_index,economy_growth,exchequer_bond_three,household_loan_all,mortgage_all,numberofnosells,unsalenum_c
date,,,,,,,,,,,
2010-01-01,0.679671,0.684444,1.0,0.644274,0.089027,1.0,1.0,0.0,0.0,0.000000,0.000000
2010-01-01,0.470226,0.684444,1.0,0.644274,0.089027,1.0,1.0,0.0,0.0,0.136113,0.026827
2010-01-01,0.659138,0.684444,1.0,0.644274,0.089027,1.0,1.0,0.0,0.0,0.136113,0.026827
2010-01-01,0.400411,0.684444,1.0,0.644274,0.089027,1.0,1.0,0.0,0.0,0.136113,0.026827
2010-01-01,0.443532,0.684444,1.0,0.644274,0.089027,1.0,1.0,0.0,0.0,0.136113,0.026827

## 3. Model & Optimizer

In [6]:
model = nn.Sequential(
            nn.Linear(input_dim,1),
   #         nn.ReLU(),
   #         nn.Linear(200,100),
   #         nn.ReLU(),
   #         nn.Linear(100,50),
   #         nn.ReLU(),
   #         nn.Linear(50,50),
   #         nn.ReLU(),
   #         nn.Linear(50,1),
        )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.01)

In [7]:
print(torch.from_numpy(X_train.values))

tensor([[0.5598, 0.6844, 1.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.1737, 0.6844, 1.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6844, 1.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.7838, 0.0889, 0.0913,  ..., 1.0000, 0.0000, 0.0000],
        [0.7220, 0.0889, 0.0913,  ..., 1.0000, 0.0000, 0.0000],
        [0.7490, 0.0889, 0.0913,  ..., 1.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

## 4. Train

In [8]:
input_data = torch.from_numpy(X_train.values).float()
label = torch.from_numpy(Y_train.values).float()
print(input_data.size())
loss_arr =[]

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(input_data)
    #print("output", output)
    #print("label", label)
    
    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    loss_arr.append(loss.item())
    print(loss.item())

torch.Size([336, 11])
0.8784438371658325
0.8456798791885376
0.8128672242164612
0.7802034020423889
0.7476019263267517
0.7151392102241516
0.6829100251197815
0.6510313153266907
0.6194756031036377
0.5885448455810547
0.5583958625793457
0.5291445255279541
0.500922679901123
0.4738326370716095
0.4478278160095215
0.42301145195961
0.3992989957332611
0.3766477406024933
0.3550584614276886
0.33437061309814453
0.3145621120929718
0.2957090437412262
0.2777961790561676
0.2607807219028473
0.2446211576461792
0.2293233424425125
0.21512369811534882
0.20242446660995483
0.19148749113082886
0.18249660730361938
0.17543555796146393
0.1700630784034729
0.16607393324375153
0.16313816606998444
0.16099748015403748
0.15945030748844147
0.15834687650203705
0.15752312541007996
0.15689383447170258
0.15638487040996552
0.15595677495002747
0.15558774769306183
0.15526017546653748
0.15495270490646362
0.15466800332069397
0.15439419448375702
0.15413567423820496
0.1538819968700409
0.15364240109920502
0.1534045785665512
0.1531698852777481
0.15293869376182556
0.15271632373332977
0.15249782800674438
0.15228088200092316
0.15206460654735565
0.1518554985523224
0.15165062248706818
0.15144146978855133
0.15124455094337463
0.15104946494102478
0.1508515179157257
0.1506575495004654
0.150467649102211
0.15028038620948792
0.15009257197380066
0.14990539848804474
0.14972707629203796
0.14954710006713867
0.14936833083629608
0.14918923377990723
0.14901649951934814
0.1488485187292099
0.1486760675907135
0.14850498735904694
0.1483357697725296
0.14817121624946594
0.14800742268562317
0.14784522354602814
0.14768445491790771
0.14752276241779327
0.14736370742321014
0.1472078114748001
0.14705170691013336
0.14689762890338898
0.1467428058385849
0.14659002423286438
0.14644160866737366
0.14628952741622925
0.1461431384086609
0.14599500596523285
0.14584869146347046
0.14570413529872894
0.14556312561035156
0.1454213410615921
0.14528058469295502
0.1451376974582672
0.14499756693840027
0.1448584496974945
0.14472319185733795
0.1445886492729187
0.14445199072360992
0.14431749284267426
0.14418569207191467
0.14405199885368347
0.14391975104808807
0.14379005134105682
0.14366021752357483
0.1435335874557495
0.1434045284986496
0.14327922463417053
0.143153116106987
0.14302824437618256
0.14290402829647064
0.14278076589107513
0.14265692234039307
0.14253538846969604
0.1424170881509781
0.1422995775938034
0.1421770304441452
0.1420593112707138
0.14194060862064362
0.14182449877262115
0.1417093276977539
0.14159218966960907
0.14147689938545227
0.1413635015487671
0.14124833047389984
0.14113621413707733
0.14102518558502197
0.1409139633178711
0.1408037692308426
0.14069579541683197
0.14058655500411987
0.14047771692276
0.1403709352016449
0.14026421308517456
0.14015908539295197
0.14005351066589355
0.13994717597961426
0.1398434042930603
0.13973937928676605
0.13963711261749268
0.13953600823879242
0.13943500816822052
0.13933239877223969
0.13923266530036926
0.13912983238697052
0.13903269171714783
0.13893535733222961
0.13883668184280396
0.13873888552188873
0.1386430859565735
0.1385456770658493
0.13844919204711914
0.1383546143770218
0.13825933635234833
0.13816462457180023
0.1380736529827118
0.1379813700914383
0.13788650929927826
0.13779516518115997
0.13770626485347748
0.13761569559574127
0.1375269591808319
0.13743947446346283
0.13735049962997437
0.13726091384887695
0.13717277348041534
0.13708965480327606
0.13700170814990997
0.1369154155254364
0.1368314027786255
0.1367494761943817
0.1366632878780365
0.13657964766025543
0.1364966779947281
0.1364150047302246
0.13633322715759277
0.13625361025333405
0.13617387413978577
0.1360929012298584
0.13601407408714294
0.13593383133411407
0.13585780560970306
0.13578036427497864
0.13570207357406616
0.13562586903572083
0.13555054366588593
0.13547536730766296
0.13539940118789673
0.135324627161026
0.1352497935295105
0.13517552614212036
0.13510294258594513
0.13503031432628632
0.1349584311246872
0.13488897681236267
0.1348184049129486
0.13474780321121216

In [9]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[ 0.3073, -0.0573, -0.1118,  0.0038,  0.3606,  0.2751,  0.3367,  0.2430,
         -0.2040, -0.0658, -0.0413]], requires_grad=True), Parameter containing:
tensor([0.1245], requires_grad=True)]

## 5. Visualize Trained Output

In [10]:
'''
‘region_cd’: ‘지역코드(시도)’,
‘year’: ‘연도’,
‘month’:’월’,
‘building_type’: ‘부동산타입’,
‘tradeprice_sido’ : ‘매매가격지수(시도)’,
‘construction_realized_amount’ : ‘건설기성액(백만원)’,
“cd”: “cd(91일물)“,
‘spirit_deposit_rate’: ‘정기예금금리’,
‘exchange_rate’: ‘환율’,
‘composite_stock_price_index’: ‘종합주가지수’,
‘economy_growth’: ‘경제성장률’,
‘exchequer_bond_three’ : ‘국고채3년‘,
‘household_loan_all’: ‘가계대출액(전국)’,
‘mortgage_all’ : ‘주택대출액(전국)’,
‘numberofnosells’:’미분양 가구수(시도)’,
‘unsalenum_c’:’공사완료후 미분양(민간,시도)’
'''

'\n‘region_cd’: ‘지역코드(시도)’,\n‘year’: ‘연도’,\n‘month’:’월’,\n‘building_type’: ‘부동산타입’,\n‘tradeprice_sido’ : ‘매매가격지수(시도)’,\n‘construction_realized_amount’ : ‘건설기성액(백만원)’,\n“cd”: “cd(91일물)“,\n‘spirit_deposit_rate’: ‘정기예금금리’,\n‘exchange_rate’: ‘환율’,\n‘composite_stock_price_index’: ‘종합주가지수’,\n‘economy_growth’: ‘경제성장률’,\n‘exchequer_bond_three’ : ‘국고채3년‘,\n‘household_loan_all’: ‘가계대출액(전국)’,\n‘mortgage_all’ : ‘주택대출액(전국)’,\n‘numberofnosells’:’미분양 가구수(시도)’,\n‘unsalenum_c’:’공사완료후 미분양(민간,시도)’\n'

## 6. Prediction

In [11]:
eval_data = torch.from_numpy(X_test.values).float()
eval_label = torch.from_numpy(Y_test.values).float()

eval_result = model(eval_data)
print(eval_result)
print(torch.nn.functional.sigmoid(eval_result))
print(eval_label)

tensor([[0.8287],
        [0.7543],
        [0.8124],
        ...,
        [0.9712],
        [0.9726],
        [0.9688]], grad_fn=<AddmmBackward>)
tensor([[0.6961],
        [0.6801],
        [0.6926],
        ...,
        [0.7254],
        [0.7256],
        [0.7249]], grad_fn=<SigmoidBackward>)
tensor([0.6764, 0.4781, 0.6618,  ..., 0.8330, 0.8309, 0.8184])

/Users/lim/anaconda3/envs/NLPApps/lib/python3.7/site-packages/torch/nn/functional.py:1332: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")

In [12]:

def normalize2(df, df_e):
    result = df_e.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df_e[feature_name] - min_value) / (max_value - min_value)
    return result


df_e = pd.read_csv("my_data.csv", parse_dates =["date"], index_col ="date")  #엑셀 파일을 읽어 df_e변수에 저장
df_e = df_e.dropna()
test_data = normalize2(df, df_e)  # 데이터를 normalize해서 0~1사이 값으로 다 바꿈!

test_input = test_data[feature_names] # 학습에 사용했던 feature들만 뽑음
test_input.head()

test_tensor = torch.from_numpy(test_input.values).float() # pytorch tensor 형태로 데이터 변환

print(model(test_tensor))

tensor([[0.7783],
        [0.7669],
        [0.7404],
        [0.7675],
        [0.7556],
        [0.7549],
        [0.7356],
        [0.7325]], grad_fn=<AddmmBackward>)